# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Spring Boot Configuration
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: stecker
    key-passsord: stecker
